### ISSUE TITLE
Explore Better Project Creation/Upgrade Algorithms

### ISSUE THREAD

**Issue by edjubuh** [purduesigbots/pros-cli2#19]
CLI should create projects as frequently as possible (w.r.t to the user's filesystem). This issue is intended to gather feedback on how `pros conduct create` should behave with non-empty target directories.

One possible solution is to always create the project, and if a file that we attempt to copy already exists, notify the user, don't copy the file, and continue on to the next file.

**Comment by ghost** [comment]
> One possible solution is to always create the project, and if a file that we attempt to copy already exists, notify the user, don't copy the file, and continue on to the next file.

This seems to me like the best way to handle such a situation. I would also suggest implementing a _-f_ or _--force_ argument that will override existing files.
