### ISSUE TITLE
Nonresponse/firmware corruption after "Asking for system info" on Microsoft Surface devices

### ISSUE THREAD

**Issue by ghost** [purduesigbots/pros-cli2#23]
#### Expected Behavior:
PROS downloads code successfully without corrupting the master firmware

#### Actual Behavior:
Once PROS reaches the "Asking for system info" stage, it repeats the "Asking for system info" message after a few seconds and then gets stuck until a keyboard interrupt (Ctrl+C) is used or the VEXnet device is unplugged.

If connected to a Cortex via a direct USB A-A cable, the master firmware also becomes corrupted and must be redownloaded.

#### Steps to reproduce:
See **Additional Information**

#### System information:
Operating System: Windows
Device(s): Microsoft Surface devices (see **Additional Information**)

PROS Version: 2.11.0

#### Additional Information
- I will continue investigating this problem for the foreseeable future to try and track down plausible causes/circumstances for the issue (including a test of a Surface Pro 3 running Ubuntu)
- This problem has manifested itself on 2 different models of Microsoft Surface devices and nowhere else that I know of, hence the theory that something about the Surfaces causes the issue
- Extremely limited [for now] testing with PROS 2.10.0 running on one of the same Surfaces that didn't work with 2.11.0 has not [yet] resulted in this issue manifesting itself (all the downloads were successful)

#### Screenshots/Output Dumps/Stack Traces
_[Will be added in a later edit]_

**Comment by edjubuh** [comment]
Barin,

Expect to need to a USB trace/log of the bytes sent/received by Cortex for your analysis. You can probably use tools such as Microsoft Message Analyzer or Wireshark.

**Comment by ghost** [comment]
Will do. However, I first have to replicate the problem on my own Surface (the Surfaces that caused problems were other people's), so it might be a while before I get back to investigating this.

**Comment by edjubuh** [comment]
@barinb1 We have PR #27 in the works that may fix some of these issues. Can you let us know if you get better performance?

**Comment by ghost** [comment]
@edjubuh Will do. My team will be competing at the state championship this weekend, but after that I'll try to find time.

Also, on a mostly related note, I've recently had some issues with the new PROS flasher outside of Surface devices too. Running 'make -k upload' under the exact same circumstances with the exact same code has worked though. So I'm almost certain there are some bugs to be ironed out.

**Comment by ghost** [comment]
@edjubuh I've started trying to replicate the issues with the current official release of the CLI (2.4.3 as reported by `pros --version`). I haven't _yet_ been able to replicate any of the issues mentioned previously, but I'll keep trying and keep this issue updated with my progress.

**Comment by ghost** [comment]
Confirmed: the issues no longer occur on the same device on which they previously occurred.
