### ISSUE TITLE
Occasionally gets stuck on "Preparing bootloader..."

### ISSUE THREAD

**Issue by jerbmega** [purduesigbots/pros-cli2#25]
#### Expected Behavior:
Downloading works 100% of the time.
#### Actual Behavior:
Download seems to have a 50% chance of getting stuck on the "Preparing bootloader..." phase. It will stay here for a little bit, then print "failed."

Sometimes it'll stick on other places too, like "Stopping user code..."
#### Steps to reproduce:
Click the Download button in Atom. Connection type doesn't seem to matter.
#### System information:
Operating System:  Windows 8.1

PROS Version: 2.4.2- 

#### Screenshots/Output Dumps/Stack Traces

Here's the output of pros flash with --debug --verbose
```
`        DEBUG: Opening C:\Users\2021PBpirates\Documents\508X\project.pros (Proje
ctConfig)
Flashing C:\Users\2021PBpirates\Documents\508X\bin/output.bin to COM5
Stopping user code...   DEBUG: 0F 0F 21 DE 08 00 00 00 08 F1 04
        DEBUG:
complete
Asking for system information...        DEBUG: SYS INFO BITS: C9 36 B8 47 21   P
ORT CFG: Serial<id=0x3092c90, open=True>(port='COM5', baudrate=115200, bytesize=
8, parity='N', stopbits=1, timeout=5.0, xonxoff=False, rtscts=False, dsrdtr=Fals
e)
        DEBUG: SYS INFO RESPONSE: F6 F3 F3 F3 F3 F3 AA 55 21 0A 00 00 04 19 00 0
0 00 20 00 04
        DEBUG: SYS INFO RESPONSE: AA 55 21 0A 00 00 04 19 00 00 00 20 00 05
complete
Cortex Microcontroller connected on COM5
  Tether: Directly w/ a USB cable
Joystick: F/W 0.0 w/ 0.00V
  Cortex: F/W 4.25 w/ 0.00V (Backup: 0.00V)
Exposing bootloader... complete
Preparing bootloader... DEBUG: STM BL RESPONSE TO 0x7F: 0D
failed`
```

**Comment by HotelCalifornia** [comment]
We're working on this over in #27
