### ISSUE TITLE
PROS CLI Missing After PC Reset

### ISSUE THREAD

**Issue by ItsMurf** [purduesigbots/pros-cli2#32]
#### System information:
Operating System: Windows

PROS Version: (run `pros --version`)

#### Additional Information
I fixed this a while back, can't exactly remember how to.

**Comment by edjubuh** [comment]
What do you mean by missing CLI? Is it not in C:\Program Files\PROS? Is it missing from PATH?

**Comment by ItsMurf** [comment]
When I start up Atom and the PROS log in screen pops up, it says CLI Missing from PATH.

**Comment by edjubuh** [comment]
What is your PATH? If the CLI is on PATH, then check where PROS is installed and make sure they match up. Atom and the PROS CLI do not modify PATH. Once it is added by the installer, PATH isn't modified by PROS.

**Comment by Matterny** [comment]
I am experiencing the same issue, I tried to install PROS on 4 different computers, windows 7 and 10, 32 bit and 64 and when I finish the installation every time I launch pros I get the error "PROS CLI was not found on your PATH! Make sure PROS CLI is installed and available on your PATH." I have successfully installed pros 2 weeks ago on Windows 10 twice. I have tried running atom as admin and installing atom first and using the pros installer.

**Comment by edjubuh** [comment]
I just ran the Windows installers on a fresh installation of Windows 10 x64 and everything worked fine. My steps were to go to pros.cs.purdue.edu/download (equivalent to [the latest release](https://github.com/purduesigbots/pros-cli/releases/tag/2.4.3)) and go through the installation process. I opened up Atom, verified on the Welcome Page that the CLI was found, then closed Atom. Waited a brief moment, and then reopened Atom and still saw the CLI.

Can you verify that `C:\Program Files (x86)\PROS\cli` is on the PATH?

**Comment by Matterny** [comment]
There is no program files pros directory

**Comment by Matterny** [comment]
OK, sorry about that, the 32 bit computer doesn't have that, while the 64 bit computers have the pros folder and the CLI folder. Both output the same error. I do not know what on the path means

**Comment by HotelCalifornia** [comment]
PATH is a system variable that lets the operating system know what directories it should look in to run executable programs.
To see what's on your PATH, type `echo %PATH%` in a command prompt window, and let us know what the output is.

**Comment by ItsMurf** [comment]
Mine just randomly began to work again, no idea what happened.

**Comment by Matterny** [comment]
Sorry it took so long, you are correct, the path is:
" C:\Users\RobotStudent>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Users\RobotStudent\AppData\Local\atom\bin"
I am a partial admin on a school computer, which may be contributing to these issues. The main admin did encounter the same issues when installing the program on an identical machine and this one, any way to get a proper installation? Currently running Sophos antivirus and a 64 bit intel machine.

**Comment by edjubuh** [comment]
If `C:\Program Files\PROS\cli` exists (may be in Program Files (x86) depending on if you're using the latest version), then just make sure that folder is on your PATH. You may also have an issue where the PROS_TOOLCHAIN variable didn't get set for the same reason PATH didn't get updated. PROS_TOOLCHAIN should point to `C:\Program Files\toolchain` so when you run `echo %PROS_TOOLCHAIN%` you should get `C:\Program Files\toolchain`.

To verify everything works, running `pros make` from command prompt and you should get something to the effect of:
```
Invoking make in ....
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by HotelCalifornia** [comment]
@Matterny any updates on your situation?

**Comment by Matterny** [comment]
I got a different computer to work, and I think running the installer software in repair more fixes it, but I can't test it due to a long approval process for software.
