### ISSUE TITLE
Uploading with some third-party COM ports fails

### ISSUE THREAD

**Issue by edjubuh** [purduesigbots/pros-cli2#36]
#### Expected Behavior:
Be able to upload projects no matter what COM ports Windows thinks exist.

#### Actual Behavior:
Some devices do not report all the information we query when checking if a COM port is a Cortex microcontroller. One example is the Arduino Uno.

#### Steps to reproduce:
Plug in a device like an Arduino Uno and attempt to upload.

#### System information:
Operating System:  Windows, but likely affects all platforms

PROS Version: 2.5.1

#### Additional Information
The issue is with https://github.com/purduesigbots/pros-cli/blob/master/prosflasher/ports.py#L16 - just need to make it type check

#### Screenshots/Output Dumps/Stack Traces
![image](https://cloud.githubusercontent.com/assets/5461357/26661804/9e5ee6de-4645-11e7-85fe-788a7f51e694.png)
![image](https://cloud.githubusercontent.com/assets/5461357/26661809/a356438a-4645-11e7-899c-6f6741521cdb.png)
![image](https://cloud.githubusercontent.com/assets/5461357/26661817/a8ff53f8-4645-11e7-8e83-bc7775940192.png)

**Comment by HotelCalifornia** [comment]
Although we do have a fix inbound (#37), the workaround for this issue in the meantime is to simply unplug the other COM device(s).
