### ISSUE TITLE
When adding a library,  the library's template.pros is copied to the project's root

### ISSUE THREAD

**Issue by BottomNotch** [purduesigbots/pros-cli2#42]
#### Expected Behavior:
`pros conduct add-lib <location> <library>` should copy the libraries .a file to the <location>/firmware, any header files to <location>/include, add itself to the project's project.pros, and to nothing else (amusing location is the root of a pros project).

#### Actual Behavior:
it behave as expected except it also copies the library's template.pros to the project root if there's not already a template.pros

#### Steps to reproduce:
make sure there isn't a template.pros in the project in which you want to install the library
`pros conduct add-lib <location> <library>`

#### System information:
Operating System:  Ubuntu

PROS Version: 2.6.0

**Comment by HotelCalifornia** [comment]
Applied a hotfix to the libblrs release which changes the `template_ignore` key to `template.pros` from `project.pros`

**Comment by edjubuh** [comment]
The @HotelCalifornia is the correct behavior, not a hotfix. We may look into making template.pros implicitly ignored which should be straightforward to do, but the current behavior works.
