### ISSUE TITLE
SSL module is not available

### ISSUE THREAD

**Issue by HotelCalifornia** [purduesigbots/pros-cli2#45]
The build environment for the PROS CLI on MacOS fails to link an SSL module (e.g. OpenSSL).

Cursory research shows that OpenSSL has been deprecated on MacOS since 10.7, and thus `homebrew` does not link it by default for Python.

Until this issue is resolved, MacOS users will not be able to download kernel or library templates as the GitHub API requires the use of SSL.

**Comment by HotelCalifornia** [comment]
Possible fixes:
- Use the official distribution of Python 3 for Mac
- Force homebrew to link OpenSSL
- Figure out how people are using Apple's home-cooked "Common Crypto"

**Comment by HotelCalifornia** [comment]
First option is the easiest, however I'm not sure it will actually solve the problem. The other issue with that option will come up when we eventually move the build process to a Jenkins script (i.e. we'll have to hard-code the URL to the python binary, and then run it using `installer`, I think)

**Comment by ben06202001** [comment]
So I had this issue and tried to resolve it.
I did (sorta)

1) I factory reseted my mac (I don't think this step is required)
2) installed High Seria
3) installed homebrew in terminal, just copy and paste:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
4) installed OpenSSL (in terminal):
brew install openssl
5) installed Python 3 (in terminal):
brew install python3
6) installed openssl with python3 (in terminal):
pip3 install pyopenssl
7) installed Atom
8) installed the PROS macOS package
9) restarted my laptop
10)was able to download kernels (but they don't always show up)

Hope this helps anyone,
And thanks to the devs :-)

**Comment by HotelCalifornia** [comment]
@ben06202001 while that is an acceptable workaround for the time being, one of the goals of the new installer experience is that users will not need to install python as a dependency, so I'm still going to attempt to fix the root problem. 
I'm not sure that updating to High Sierra is strictly necessary, but my personal opinion with respect to computer updates is that they're generally a good thing.
Also, allegedly Apple has deprecated OpenSSL, so I'm not sure that recommending users install it is the right course of action.

Either way, as I said your suggestion is an acceptable workaround for the issue, for now.

**Comment by HotelCalifornia** [comment]
I guess this needs more of an update.

I haven't checked to see if this is still an issue after moving to circleci for building on macOS, but I can start looking into that next week.

Some things to check for:
- can High Sierra users download templates?
- verify that versions prior to High Sierra still work as intended
- optionally figure out _why_ things work, if they do

this is still of semi-high priority, as this will likely be an issue with upcoming versions of the CLI if left unchecked

**Comment by HotelCalifornia** [comment]
It seems that building on Sierra instead of High Sierra may have fixed some of these issues. Moving forward, this won't be a problem as the new version of the CLI is installed entirely through Homebrew (or pip).
