### ISSUE TITLE
Windows: 2.5.1 to 2.6.1 Update Issues (Environment Variables, Double Installation)

### ISSUE THREAD

**Issue by ghost** [purduesigbots/pros-cli2#46]
### Comment updated with more thorough information:
The PROS installer for 2.5.1 would, by default, install PROS in Program Files and appropriately set/modify the `PROS_TOOLCHAIN` and `Path` _user_ environment variables (inconsistent).

The 2.6.1 installer gives the choice of a system-wide or user-specific installation.
- Choosing system-wide defaults to PROS being installed in Program Files and setting/modifying the `PROS_TOOLCHAIN` and `Path` _system_ environment variables (correct practice).
- Choosing user-specific defaults to an installation directory in AppData and setting/modifying the `PROS_TOOLCHAIN` and `Path` _user_ environment variables (also correct practice).

**Because of this inconsistency between the versions, updating from v2.5.1 to v2.6.1 through the standard installer does not work properly:**
- Choosing to install v2.6.1 system-wide correctly overwrites the files from v2.5.1, but fails to update environment variables properly: the old _user_ environment variables remain unchanged, while new entries are added to _system_ environment variables. Running `pros make` consequently fails (outputting a stack trace) as it first sees the _user_ (unchanged from v2.5.1) `PROS_TOOLCHAIN` environment variable and the GCC update with v2.6.1 requires `PROS_TOOLCHAIN` to point to a slightly different directory.
- Choosing to install v2.6.1 for only the current user correctly updates the _user_ environment variables (that were set previously for v2.5.1) and does not immediately appear to have any issues. However, this installation method actually leaves the previous Program Files installation of PROS completely intact and results in _two_ separate entries for PROS in Programs and Features (one for v2.5.1, one for v2.6.1).

**Comment by edjubuh** [comment]
Can you verify that PROS_TOOLCHAIN isn't updated by looking at the system settings page.

You can run `rundll32 sysdm.cpl,EditEnvironmentVariables` from command prompt or the Run prompt to get there directly

**Comment by ghost** [comment]
Initial comment updated with more thorough information.

**Comment by edjubuh** [comment]
Looks like this is a limitation of Windows Installer. You can google something along the lines of "advanced installer per user to per machine upgrade", but our best solution is going to be some custom search/action to detect the current version and simply attempt to preserve the installation type. There doesn't appear to be way to get a per-user to per-machine upgrade (or vice-versa) to automatically uninstall the older version. I'll have to look into this, but I'm going to make this issue low priority for myself until the next major release of the PROS CLI, unless someone takes a look at the advanced installer project.
