### ISSUE TITLE
ImportError: bad magic number in 'prosconductor.providers.githubreleases': b'3\r\r\n' on macOS with PROS CLI 2.6.1

### ISSUE THREAD

**Issue by Tohoma** [purduesigbots/pros-cli2#48]
#### Expected Behavior:
After following the setup instructions on the site, Atom claimed I had an outdated cli. And after cloning  this repository and installing via pip3. The message still stayed the same. So I attempted to run pros from the command line and got the following output.

#### Steps to reproduce:
1. run pros-MacOs.pkg from website.
2. open Atom
3. install pros package and dependencies
4. clone and install this repo with pip3
5. In the terminal type pros
#### System information:
Operating System:  (Windows, OS X, Ubuntu)
OSX 10.13.1
PROS Version: (run `pros --version`)
Version 2.6.1
#### Additional Information
I was able to get pros working by commenting out  line 19 in /Users/pcross/pros-cli/prosconductor/providers/utils.py. spec.loader.load_module() and I was able to get the pros-cli working and it supposedly fixes the atom version number. However I encounter a parsing error. I find that you can download the kernel via command line and ignore the message and start a new project.

#### Screenshots/Output Dumps/Stack Traces
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/pros", line 9, in <module>
    load_entry_point('pros-cli', 'console_scripts', 'pros')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/pcross/pros-cli/proscli/__init__.py", line 5, in <module>
    from proscli.conductor import conductor_cli
  File "/Users/pcross/pros-cli/proscli/conductor.py", line 101, in <module>
    @click.option('--registrar', metavar='REGISTRAR', prompt=True, type=click.Choice(available_providers()),
  File "/Users/pcross/pros-cli/proscli/conductor.py", line 83, in available_providers
    return utils.get_all_provider_types().keys()
  File "/Users/pcross/pros-cli/prosconductor/providers/utils.py", line 19, in get_all_provider_types
    spec.loader.load_module()
ImportError: bad magic number in 'prosconductor.providers.githubreleases': b'3\r\r\n'
```

_Edit from PROS team: the following solution is not recommended. See comments below._
Update
@edjubuh I found that running find . -name "*.pyc" -delete on PROS Editor.app and PROS CLI.app appears to solve the problem. Everything appears to operate as documented.

**Comment by edjubuh** [comment]
Can you run `pros conduct first-run --apply-providers --no-force --no-download --use-defaults`?

**Comment by Tohoma** [comment]
Running that in the terminal with the uncommented line produces the same error message.

**Comment by edjubuh** [comment]
Can you paste the contents of your `~/Library/Application Support/PROS/cli.pros`?

**Comment by Tohoma** [comment]
{"py/object": "prosconfig.cliconfig.CliConfig", "py/state": {"default_libraries": [], "providers": ["/Applications/PROS CLI.app/Contents/MacOS/lib/prosconductor/providers/githubreleases.pyc"]}}

**Comment by edjubuh** [comment]
I see you've edited your original issue that it's been fixed.

**Comment by edjubuh** [comment]
To anyone seeing this issue in the future: the "solution" mentioned above is **not** recommended. You should probably [open an issue on this repo](https://github.com/purduesigbots/pros-cli/issues/new) to help troubleshoot, but before doing so, make sure you only have one version of PROS installed (either via `pip` or through our installers) and delete `~/Library/Application Support/PROS/cli.pros`
