### ISSUE TITLE
Error Running pros make TypeError: join() argument must be str or bytes, not 'NoneType'

### ISSUE THREAD

**Issue by Highway-Man** [purduesigbots/pros-cli2#52]
#### Expected Behavior:
Attempting to build a project from command line using pros make

#### Actual Behavior:
returns type error as shown below

#### Steps to reproduce:
I started over with a clean slate after not being able to get atom to work and decided to just work on getting the cli working. Downloaded the cli repository, installed python 3.5.4, ran pip install on the repo, created a new project, said yes to depot and downloading latest kernel, ran pros make on new project.

Everything seems to work up until the last step, maybe I'm missing a step somewhere though

#### System information:
Operating System:  (Windows, OS X, Ubuntu)
Windows 10 32bit

PROS Version: (run `pros --version`)
2.6.1

#### Screenshots/Output Dumps/Stack Traces
C:\Users\Jacob\proj>pros make
Traceback (most recent call last):
  File "C:\Python35-32\Scripts\pros-script.py", line 11, in <module>
    load_entry_point('pros-cli', 'console_scripts', 'pros')()
  File "c:\users\jacob\downloads\pros-cli-master\pros-cli-master\proscli\main.py", line 9, in main
    cli.main(prog_name='pros')
  File "c:\python35-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python35-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python35-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python35-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python35-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\jacob\downloads\pros-cli-master\pros-cli-master\proscli\build.py", line 32, in make
    cmd = os.path.join(os.environ.get('PROS_TOOLCHAIN'), 'bin', 'make.exe')
  File "c:\python35-32\lib\ntpath.py", line 113, in join
    genericpath._check_arg_types('join', path, *paths)
  File "c:\python35-32\lib\genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by edjubuh** [comment]
Do you have the toolchain installed and `PROS_TOOLCHAIN` set?

**Comment by Highway-Man** [comment]
no, where do I get the toolchain from?
Do I have to use the installer or is it possible to download it manually?

**Comment by Highway-Man** [comment]
Fixed that by running installer with the editor unchecked
![image](https://user-images.githubusercontent.com/6628697/33955455-dca89d02-dff8-11e7-98a2-c3f59c9c741e.png)
Now PATH and PROS_TOOLCHAIN appear to be set correctly and I checked that those directories exist

This is the new error

> C:\Users\Jacob\proj>pros make
> Invoking make in C:\Users\Jacob\proj...
> Traceback (most recent call last):
>   File "C:\Python35-32\Scripts\pros-script.py", line 11, in <module>
>     load_entry_point('pros-cli', 'console_scripts', 'pros')()
>   File "c:\users\jacob\downloads\pros-cli-master\pros-cli-master\proscli\main.py", line 9, in main
>     cli.main(prog_name='pros')
>   File "c:\python35-32\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "c:\python35-32\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\python35-32\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\python35-32\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "c:\python35-32\lib\site-packages\click\decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "c:\users\jacob\downloads\pros-cli-master\pros-cli-master\proscli\build.py", line 40, in make
>     stdout=sys.stdout, stderr=sys.stderr)
>   File "c:\python35-32\lib\subprocess.py", line 676, in __init__
>     restore_signals, start_new_session)
>   File "c:\python35-32\lib\subprocess.py", line 957, in _execute_child
>     startupinfo)
> OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
