### ISSUE TITLE
Can you give me a link to install PROS-CLI3?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-cli2#56]
ares@aresUbuntu:~$ sudo python3.6 -m pip install PROS-CLI3
The directory '/home/ares/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ares/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting PROS-CLI3
  Could not find a version that satisfies the requirement PROS-CLI3 (from versions: )
No matching distribution found for PROS-CLI3

The world championships are over. More free. I want to learn PROS3 ahead of time.

**Comment by Octogonapus** [comment]
The CLI for PROS 3 is not released yet.

**Comment by edjubuh** [comment]
As @Octogonapus said, the CLI for PROS 3 is not released yet. Expect updates in the next month or two - we want you to be able to start using PROS 3 over the summer. Check https://pros.cs.purdue.edu/v5/blog or on the VEX Forum for updates.
