### ISSUE TITLE
ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by matthewpi** [purduesigbots/pros-cli2#65]
#### Expected Behavior:
The CLI works fine without any errors thrown.

#### Actual Behavior:
The CLI throws an error.

#### Steps to reproduce:
1

#### System information:
Operating System: Fedora 29 Beta
PROS Version: Unknown, CLI won't work
Python Version: 3.7.1

#### Additional Information
The python bin commands work perfectly fine (python, python3).

#### Screenshots/Output Dumps/Stack Traces
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007ff24c27e740 (most recent call first):
Aborted (core dumped)
```

**Comment by edjubuh** [comment]
What version or how were you trying to install?

**Comment by matthewpi** [comment]
@edjubuh I downloaded the RPM package for x86_64 from the releases page.

**Comment by matthewpi** [comment]
I converted one of the `.deb` files to `.rpm` by using `alien` and installed it.  This issue is now resolved.
